name: fluttered_micro
description: A package for scaffolding Flutter apps
version: 1.0.0+8
homepage:

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter:

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: